name:

defaults:
  run:
    working-directory: .

on:
  workflow_dispatch:
  push:
    branches:
      - "main*"
      - "dev/**"
    paths:
      - "packages/credbull/**"
      - ".github/workflows/**"
  schedule:
    - cron: '50 13 * * *'  # 1:50 PM GMT / 9:50 AM ET
    - cron: '0 14 * * *'   # 2:00 PM GMT / 10:00 AM ET
    - cron: '10 14 * * *'  # 2:10 PM GMT / 10:10 AM ET

jobs:
  liquid-stone-ops:
    runs-on: ubuntu-latest
    environment: local

    steps:
      - name: Checkout credbull-sdk
        uses: actions/checkout@v4

      - name: Install yarn
        run: |
          corepack enable
          yarn set version stable

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Project Dependencies
        run: yarn install

      - name: Run LiquidStone Plume Legacy (ETH) Ops Scripts
        run: yarn run-liquid-stone-legacy-ops --verbose
        working-directory: packages/credbull
        env:
          THIRDWEB_CLIENT_ID: ${{ secrets.CREDBULL_DEVOPS_THIRDWEB_CLIENT_ID }}
          ALCHEMY_API_KEY: ${{ secrets.CREDBULL_DEVOPS_ALCHEMY_API_KEY }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.CREDBULL_DEVOPS_DEPLOYER_PRIVATE_KEY }}
          DEPLOYER_ALT_PRIVATE_KEY: ${{ secrets.CREDBULL_DEVOPS_DEPLOYER_ALT_PRIVATE_KEY }}
          USER_PRIVATE_KEY: ${{ secrets.CREDBULL_DEVOPS_CHARLIE_PRIVATE_KEY }}
          USER_ADDRESS: ${{ secrets.CREDBULL_DEVOPS_CHARLIE_ADDRESS }}

      - name: Run LiquidStone Plume ($PLUME) Ops Scripts
        run: yarn run-liquid-stone-ops --verbose
        working-directory: packages/credbull
        env:
          THIRDWEB_CLIENT_ID: ${{ secrets.CREDBULL_DEVOPS_THIRDWEB_CLIENT_ID }}
          ALCHEMY_API_KEY: ${{ secrets.CREDBULL_DEVOPS_ALCHEMY_API_KEY }}
          DEPLOYER_ALT_PRIVATE_KEY: ${{ secrets.CREDBULL_DEVOPS_DEPLOYER_ALT_PRIVATE_KEY }}
          USER_PRIVATE_KEY: ${{ secrets.CREDBULL_DEVOPS_CHARLIE_PRIVATE_KEY }}
          USER_ADDRESS: ${{ secrets.CREDBULL_DEVOPS_CHARLIE_ADDRESS }}

      - name: Run BlackOpal Fund Ops Scripts
        run: yarn run-fund-ops --verbose
        working-directory: packages/credbull
        env:
          THIRDWEB_CLIENT_ID: ${{ secrets.CREDBULL_DEVOPS_THIRDWEB_CLIENT_ID }}
          ALCHEMY_API_KEY: ${{ secrets.CREDBULL_DEVOPS_ALCHEMY_API_KEY }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.CREDBULL_DEVOPS_DEPLOYER_PRIVATE_KEY }}
          DEPLOYER_ALT_PRIVATE_KEY: ${{ secrets.CREDBULL_DEVOPS_DEPLOYER_ALT_PRIVATE_KEY }}
          USER_PRIVATE_KEY: ${{ secrets.CREDBULL_DEVOPS_CHARLIE_PRIVATE_KEY }}
          USER_ADDRESS: ${{ secrets.CREDBULL_DEVOPS_CHARLIE_ADDRESS }}

